///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Mycalcu
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MycalcuRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("8bbab2f3-0672-4fed-a877-513b7a493abb")]
    public partial class MycalcuRepository : RepoGenBaseFolder
    {
        static MycalcuRepository instance = new MycalcuRepository();
        MycalcuRepositoryFolders.CalculatorAppFolder _calculator;

        /// <summary>
        /// Gets the singleton class instance representing the MycalcuRepository element repository.
        /// </summary>
        [RepositoryFolder("8bbab2f3-0672-4fed-a877-513b7a493abb")]
        public static MycalcuRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MycalcuRepository() 
            : base("MycalcuRepository", "/", null, 0, false, "8bbab2f3-0672-4fed-a877-513b7a493abb", ".\\RepositoryImages\\MycalcuRepository8bbab2f3.rximgres")
        {
            _calculator = new MycalcuRepositoryFolders.CalculatorAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("8bbab2f3-0672-4fed-a877-513b7a493abb")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Calculator folder.
        /// </summary>
        [RepositoryFolder("310e17de-5bfb-4251-ab8d-8ce24ee4f36f")]
        public virtual MycalcuRepositoryFolders.CalculatorAppFolder Calculator
        {
            get { return _calculator; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MycalcuRepositoryFolders
    {
        /// <summary>
        /// The CalculatorAppFolder folder.
        /// </summary>
        [RepositoryFolder("310e17de-5bfb-4251-ab8d-8ce24ee4f36f")]
        public partial class CalculatorAppFolder : RepoGenBaseFolder
        {
            MycalcuRepositoryFolders.NumberPadFolder _numberpad;
            RepoItemInfo _plusbuttonInfo;
            RepoItemInfo _equalbuttonInfo;
            RepoItemInfo _headerInfo;
            RepoItemInfo _minusbuttonInfo;
            RepoItemInfo _sometextInfo;
            RepoItemInfo _clearbuttonInfo;
            RepoItemInfo _togglepanebuttonInfo;

            /// <summary>
            /// Creates a new Calculator  folder.
            /// </summary>
            public CalculatorAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Calculator", "/winapp[@packagename='Microsoft.WindowsCalculator']", parentFolder, 30000, null, true, "310e17de-5bfb-4251-ab8d-8ce24ee4f36f", "")
            {
                _numberpad = new MycalcuRepositoryFolders.NumberPadFolder(this);
                _plusbuttonInfo = new RepoItemInfo(this, "PlusButton", ".//container[@automationid='StandardOperators']/button[@automationid='plusButton']", ".//button[@automationid='plusButton']", 30000, null, "71a4f89f-a143-4af9-9fa9-927bd2f62d33");
                _equalbuttonInfo = new RepoItemInfo(this, "EqualButton", ".//container[@automationid='StandardOperators']/button[@automationid='equalButton']", ".//button[@automationid='equalButton']", 30000, null, "e1f6bf84-59b6-4523-b0f2-c3993775fbcc");
                _headerInfo = new RepoItemInfo(this, "Header", "?/?/text[@automationid='Header']", "?/?/text[@automationid='Header']", 30000, null, "9296e89f-f629-43b1-aa59-25a41f0e7fa5");
                _minusbuttonInfo = new RepoItemInfo(this, "MinusButton", ".//container[@automationid='StandardOperators']/button[@automationid='minusButton']", ".//button[@automationid='minusButton']", 30000, null, "122b313e-c8ce-4c2c-92a0-b95f980a5cc0");
                _sometextInfo = new RepoItemInfo(this, "SomeText", ".//container[@automationid='StandardOperators']/button[@automationid='equalButton']/text[@name='']", ".//text[@name='']", 30000, null, "7b4e06ac-b29a-492d-9adf-458ffc1c7f18");
                _clearbuttonInfo = new RepoItemInfo(this, "ClearButton", ".//container[@automationid='DisplayControls']/button[@automationid='clearButton']", ".//button[@automationid='clearButton']", 30000, null, "d3d70433-20eb-46db-af34-47dc7a41ea00");
                _togglepanebuttonInfo = new RepoItemInfo(this, "TogglePaneButton", "?/?/button[@automationid='TogglePaneButton']", "?/?/button[@automationid='TogglePaneButton']", 30000, null, "ac1f3c44-ee9c-40a7-9cd1-75c6093326ab");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("310e17de-5bfb-4251-ab8d-8ce24ee4f36f")]
            public virtual Ranorex.WindowsApp Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WindowsApp>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("310e17de-5bfb-4251-ab8d-8ce24ee4f36f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The PlusButton item.
            /// </summary>
            [RepositoryItem("71a4f89f-a143-4af9-9fa9-927bd2f62d33")]
            public virtual Ranorex.Button PlusButton
            {
                get
                {
                    return _plusbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The PlusButton item info.
            /// </summary>
            [RepositoryItemInfo("71a4f89f-a143-4af9-9fa9-927bd2f62d33")]
            public virtual RepoItemInfo PlusButtonInfo
            {
                get
                {
                    return _plusbuttonInfo;
                }
            }

            /// <summary>
            /// The EqualButton item.
            /// </summary>
            [RepositoryItem("e1f6bf84-59b6-4523-b0f2-c3993775fbcc")]
            public virtual Ranorex.Button EqualButton
            {
                get
                {
                    return _equalbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The EqualButton item info.
            /// </summary>
            [RepositoryItemInfo("e1f6bf84-59b6-4523-b0f2-c3993775fbcc")]
            public virtual RepoItemInfo EqualButtonInfo
            {
                get
                {
                    return _equalbuttonInfo;
                }
            }

            /// <summary>
            /// The Header item.
            /// </summary>
            [RepositoryItem("9296e89f-f629-43b1-aa59-25a41f0e7fa5")]
            public virtual Ranorex.Text Header
            {
                get
                {
                    return _headerInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Header item info.
            /// </summary>
            [RepositoryItemInfo("9296e89f-f629-43b1-aa59-25a41f0e7fa5")]
            public virtual RepoItemInfo HeaderInfo
            {
                get
                {
                    return _headerInfo;
                }
            }

            /// <summary>
            /// The MinusButton item.
            /// </summary>
            [RepositoryItem("122b313e-c8ce-4c2c-92a0-b95f980a5cc0")]
            public virtual Ranorex.Button MinusButton
            {
                get
                {
                    return _minusbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The MinusButton item info.
            /// </summary>
            [RepositoryItemInfo("122b313e-c8ce-4c2c-92a0-b95f980a5cc0")]
            public virtual RepoItemInfo MinusButtonInfo
            {
                get
                {
                    return _minusbuttonInfo;
                }
            }

            /// <summary>
            /// The SomeText item.
            /// </summary>
            [RepositoryItem("7b4e06ac-b29a-492d-9adf-458ffc1c7f18")]
            public virtual Ranorex.Text SomeText
            {
                get
                {
                    return _sometextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SomeText item info.
            /// </summary>
            [RepositoryItemInfo("7b4e06ac-b29a-492d-9adf-458ffc1c7f18")]
            public virtual RepoItemInfo SomeTextInfo
            {
                get
                {
                    return _sometextInfo;
                }
            }

            /// <summary>
            /// The ClearButton item.
            /// </summary>
            [RepositoryItem("d3d70433-20eb-46db-af34-47dc7a41ea00")]
            public virtual Ranorex.Button ClearButton
            {
                get
                {
                    return _clearbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ClearButton item info.
            /// </summary>
            [RepositoryItemInfo("d3d70433-20eb-46db-af34-47dc7a41ea00")]
            public virtual RepoItemInfo ClearButtonInfo
            {
                get
                {
                    return _clearbuttonInfo;
                }
            }

            /// <summary>
            /// The TogglePaneButton item.
            /// </summary>
            [RepositoryItem("ac1f3c44-ee9c-40a7-9cd1-75c6093326ab")]
            public virtual Ranorex.Button TogglePaneButton
            {
                get
                {
                    return _togglepanebuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The TogglePaneButton item info.
            /// </summary>
            [RepositoryItemInfo("ac1f3c44-ee9c-40a7-9cd1-75c6093326ab")]
            public virtual RepoItemInfo TogglePaneButtonInfo
            {
                get
                {
                    return _togglepanebuttonInfo;
                }
            }

            /// <summary>
            /// The NumberPad folder.
            /// </summary>
            [RepositoryFolder("a400a1ee-ba62-4a97-a40f-d33790cde0bd")]
            public virtual MycalcuRepositoryFolders.NumberPadFolder NumberPad
            {
                get { return _numberpad; }
            }
        }

        /// <summary>
        /// The NumberPadFolder folder.
        /// </summary>
        [RepositoryFolder("a400a1ee-ba62-4a97-a40f-d33790cde0bd")]
        public partial class NumberPadFolder : RepoGenBaseFolder
        {
            RepoItemInfo _num2buttonInfo;
            RepoItemInfo _text2Info;
            RepoItemInfo _num3buttonInfo;
            RepoItemInfo _num5buttonInfo;
            RepoItemInfo _text3Info;
            RepoItemInfo _num6buttonInfo;
            RepoItemInfo _num1buttonInfo;
            RepoItemInfo _num4buttonInfo;
            RepoItemInfo _num8buttonInfo;

            /// <summary>
            /// Creates a new NumberPad  folder.
            /// </summary>
            public NumberPadFolder(RepoGenBaseFolder parentFolder) :
                    base("NumberPad", ".//container[@automationid='NumberPad']", parentFolder, 30000, null, false, "a400a1ee-ba62-4a97-a40f-d33790cde0bd", "")
            {
                _num2buttonInfo = new RepoItemInfo(this, "Num2Button", "button[@automationid='num2Button']", "", 30000, null, "c19d65b4-4d4d-48fa-b10b-bacf12bccf1b");
                _text2Info = new RepoItemInfo(this, "Text2", "button[@automationid='num2Button']/text[@name='2']", "", 30000, null, "dfa8f8e7-8a92-47f9-9974-e663d236a953");
                _num3buttonInfo = new RepoItemInfo(this, "Num3Button", "button[@automationid='num3Button']", "", 30000, null, "543017e3-8ca4-4df4-a714-5e49937baa1c");
                _num5buttonInfo = new RepoItemInfo(this, "Num5Button", "button[@automationid='num5Button']", "", 30000, null, "53fdfe44-0bb3-4afd-9d7e-4e039bccb717");
                _text3Info = new RepoItemInfo(this, "Text3", "button[@automationid='num3Button']/text[@name='3']", "", 30000, null, "a2511167-30f8-4eb0-8107-1cb8dc6b85c2");
                _num6buttonInfo = new RepoItemInfo(this, "Num6Button", "button[@automationid='num6Button']", "", 30000, null, "a0306f33-104a-490d-a5bb-6648dbd987c7");
                _num1buttonInfo = new RepoItemInfo(this, "Num1Button", "button[@automationid='num1Button']", "", 30000, null, "e96e78fa-1d21-4dd4-90bc-63d5861d776a");
                _num4buttonInfo = new RepoItemInfo(this, "Num4Button", "button[@automationid='num4Button']", "", 30000, null, "3136aaf3-1e53-4822-bdd2-ae10a2808a5d");
                _num8buttonInfo = new RepoItemInfo(this, "Num8Button", "button[@automationid='num8Button']", "", 30000, null, "b4c627f4-481f-460c-ad70-1652b691f4a6");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a400a1ee-ba62-4a97-a40f-d33790cde0bd")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a400a1ee-ba62-4a97-a40f-d33790cde0bd")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Num2Button item.
            /// </summary>
            [RepositoryItem("c19d65b4-4d4d-48fa-b10b-bacf12bccf1b")]
            public virtual Ranorex.Button Num2Button
            {
                get
                {
                    return _num2buttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Num2Button item info.
            /// </summary>
            [RepositoryItemInfo("c19d65b4-4d4d-48fa-b10b-bacf12bccf1b")]
            public virtual RepoItemInfo Num2ButtonInfo
            {
                get
                {
                    return _num2buttonInfo;
                }
            }

            /// <summary>
            /// The Text2 item.
            /// </summary>
            [RepositoryItem("dfa8f8e7-8a92-47f9-9974-e663d236a953")]
            public virtual Ranorex.Text Text2
            {
                get
                {
                    return _text2Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text2 item info.
            /// </summary>
            [RepositoryItemInfo("dfa8f8e7-8a92-47f9-9974-e663d236a953")]
            public virtual RepoItemInfo Text2Info
            {
                get
                {
                    return _text2Info;
                }
            }

            /// <summary>
            /// The Num3Button item.
            /// </summary>
            [RepositoryItem("543017e3-8ca4-4df4-a714-5e49937baa1c")]
            public virtual Ranorex.Button Num3Button
            {
                get
                {
                    return _num3buttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Num3Button item info.
            /// </summary>
            [RepositoryItemInfo("543017e3-8ca4-4df4-a714-5e49937baa1c")]
            public virtual RepoItemInfo Num3ButtonInfo
            {
                get
                {
                    return _num3buttonInfo;
                }
            }

            /// <summary>
            /// The Num5Button item.
            /// </summary>
            [RepositoryItem("53fdfe44-0bb3-4afd-9d7e-4e039bccb717")]
            public virtual Ranorex.Button Num5Button
            {
                get
                {
                    return _num5buttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Num5Button item info.
            /// </summary>
            [RepositoryItemInfo("53fdfe44-0bb3-4afd-9d7e-4e039bccb717")]
            public virtual RepoItemInfo Num5ButtonInfo
            {
                get
                {
                    return _num5buttonInfo;
                }
            }

            /// <summary>
            /// The Text3 item.
            /// </summary>
            [RepositoryItem("a2511167-30f8-4eb0-8107-1cb8dc6b85c2")]
            public virtual Ranorex.Text Text3
            {
                get
                {
                    return _text3Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text3 item info.
            /// </summary>
            [RepositoryItemInfo("a2511167-30f8-4eb0-8107-1cb8dc6b85c2")]
            public virtual RepoItemInfo Text3Info
            {
                get
                {
                    return _text3Info;
                }
            }

            /// <summary>
            /// The Num6Button item.
            /// </summary>
            [RepositoryItem("a0306f33-104a-490d-a5bb-6648dbd987c7")]
            public virtual Ranorex.Button Num6Button
            {
                get
                {
                    return _num6buttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Num6Button item info.
            /// </summary>
            [RepositoryItemInfo("a0306f33-104a-490d-a5bb-6648dbd987c7")]
            public virtual RepoItemInfo Num6ButtonInfo
            {
                get
                {
                    return _num6buttonInfo;
                }
            }

            /// <summary>
            /// The Num1Button item.
            /// </summary>
            [RepositoryItem("e96e78fa-1d21-4dd4-90bc-63d5861d776a")]
            public virtual Ranorex.Button Num1Button
            {
                get
                {
                    return _num1buttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Num1Button item info.
            /// </summary>
            [RepositoryItemInfo("e96e78fa-1d21-4dd4-90bc-63d5861d776a")]
            public virtual RepoItemInfo Num1ButtonInfo
            {
                get
                {
                    return _num1buttonInfo;
                }
            }

            /// <summary>
            /// The Num4Button item.
            /// </summary>
            [RepositoryItem("3136aaf3-1e53-4822-bdd2-ae10a2808a5d")]
            public virtual Ranorex.Button Num4Button
            {
                get
                {
                    return _num4buttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Num4Button item info.
            /// </summary>
            [RepositoryItemInfo("3136aaf3-1e53-4822-bdd2-ae10a2808a5d")]
            public virtual RepoItemInfo Num4ButtonInfo
            {
                get
                {
                    return _num4buttonInfo;
                }
            }

            /// <summary>
            /// The Num8Button item.
            /// </summary>
            [RepositoryItem("b4c627f4-481f-460c-ad70-1652b691f4a6")]
            public virtual Ranorex.Button Num8Button
            {
                get
                {
                    return _num8buttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Num8Button item info.
            /// </summary>
            [RepositoryItemInfo("b4c627f4-481f-460c-ad70-1652b691f4a6")]
            public virtual RepoItemInfo Num8ButtonInfo
            {
                get
                {
                    return _num8buttonInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
