///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Mycalcu
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording2 recording.
    /// </summary>
    [TestModule("60fd12fc-6d86-4cbb-a61b-df0ebd22547b", ModuleType.Recording, 1)]
    public partial class Recording2 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MycalcuRepository repository.
        /// </summary>
        public static MycalcuRepository repo = MycalcuRepository.Instance;

        static Recording2 instance = new Recording2();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording2()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording2 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculator.NumberPad.Text3' at 8;16.", repo.Calculator.NumberPad.Text3Info, new RecordItemIndex(0));
            repo.Calculator.NumberPad.Text3.Click("8;16");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'Calculator.NumberPad.Num3Button' at 50;33.", repo.Calculator.NumberPad.Num3ButtonInfo, new RecordItemIndex(1));
            repo.Calculator.NumberPad.Num3Button.Click(System.Windows.Forms.MouseButtons.Right, "50;33");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculator.NumberPad.Num3Button' at 50;33.", repo.Calculator.NumberPad.Num3ButtonInfo, new RecordItemIndex(2));
            repo.Calculator.NumberPad.Num3Button.Click("50;33");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'Calculator.MinusButton' at 30;40.", repo.Calculator.MinusButtonInfo, new RecordItemIndex(3));
            repo.Calculator.MinusButton.Click(System.Windows.Forms.MouseButtons.Right, "30;40");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculator.MinusButton' at 30;40.", repo.Calculator.MinusButtonInfo, new RecordItemIndex(4));
            repo.Calculator.MinusButton.Click("30;40");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculator.NumberPad.Num6Button' at 41;34.", repo.Calculator.NumberPad.Num6ButtonInfo, new RecordItemIndex(5));
            repo.Calculator.NumberPad.Num6Button.Click("41;34");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'Calculator.NumberPad.Num6Button' at 41;34.", repo.Calculator.NumberPad.Num6ButtonInfo, new RecordItemIndex(6));
            repo.Calculator.NumberPad.Num6Button.Click(System.Windows.Forms.MouseButtons.Right, "41;34");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculator.NumberPad.Num6Button' at 41;34.", repo.Calculator.NumberPad.Num6ButtonInfo, new RecordItemIndex(7));
            repo.Calculator.NumberPad.Num6Button.Click("41;34");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculator.MinusButton' at 37;39.", repo.Calculator.MinusButtonInfo, new RecordItemIndex(8));
            repo.Calculator.MinusButton.Click("37;39");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculator.MinusButton' at 37;39.", repo.Calculator.MinusButtonInfo, new RecordItemIndex(9));
            repo.Calculator.MinusButton.Click("37;39");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculator.NumberPad.Num6Button' at 36;27.", repo.Calculator.NumberPad.Num6ButtonInfo, new RecordItemIndex(10));
            repo.Calculator.NumberPad.Num6Button.Click("36;27");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculator.SomeText' at 3;9.", repo.Calculator.SomeTextInfo, new RecordItemIndex(11));
            repo.Calculator.SomeText.Click("3;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculator.SomeText' at 3;9.", repo.Calculator.SomeTextInfo, new RecordItemIndex(12));
            repo.Calculator.SomeText.Click("3;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Standard') on item 'Calculator.Header'.", repo.Calculator.HeaderInfo, new RecordItemIndex(13));
            Validate.AttributeEqual(repo.Calculator.HeaderInfo, "Text", "Standard");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
